client-security-matchers: >
  /login/**,
  /oauth2/**,
  /logout/**,
  /en/**,
  /auth/**,
  /business/**,
  /profile/**

client-permit-matchers: >
  /login/**,
  /oauth2/**,
  /en/**,
  /auth/**,
  /error/**,
  /actuator/**,
  /info/**,
  /health/**,
  /prometheus/**,
  /business/**,
  /profile/**

spring:
  security:
    oauth2:
      client:
        provider:
          yelp:
            issuer-uri: http://127.0.0.1:8080
        registration:
          yelp:
            provider: yelp
            client-id: nextjs
            client-secret: nextjs
            authorization-grant-type:
              - authorization_code
            scope: openid, profile, email
            redirect-uri: http://127.0.0.1:8085/login/oauth2/code/nextjs
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin Access-Control-Request-Headers
        - SaveSession
      routes:
        - id: business-route
          uri: lb://business
          predicates:
            - Path=/api/v1/categories/**
          filters:
            - TokenRelay=
            - RewritePath=/categories/(?<segment>.*),/$\{segment}
        - id: nextjs
          uri: http://localhost:3000
          predicates:
            - Path=/**
        - id: identity-route
          uri: lb://identity
          predicates:
            - Path=/identity/**
          filters:
            - TokenRelay=
            - RewritePath=/identity/(?<segment>.*),/$\{segment}