spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      routes:
        - id: business-route
          uri: lb://business
          predicates:
            - Path=/api/v1/categories/**
        - id: nextjs
          uri: http://localhost:3000
          predicates:
            - Path=/**